name: check

on: [pull_request, push]

jobs:
  mix_check:
    name: mix check (Elixir ${{matrix.elixir}}, OTP ${{matrix.otp}})

    strategy:
      matrix:
        otp: ["24", "25", "26"]
        elixir: ["1.14"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache Elixir deps
        uses: actions/cache@v2
        with:
          path: deps
          key: elixir-deps-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            elixir-deps-${{ runner.os }}-

      - name: Fetch Elixir deps
        run: mix deps.get

      - name: Cache Elixir build
        uses: actions/cache@v2
        with:
          path: _build
          key: elixir-build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-${{ hashFiles('lib/**/*.ex', 'config/*.exs', 'mix.exs') }}
          restore-keys: |
            elixir-build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-
            elixir-build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Compile Elixir deps
        run: mix deps.compile

      - name: Run unit test
        run: mix test
