name: check

on: [pull_request, push]

jobs:
  mix_check:
    name: mix check (Elixir ${{matrix.elixir}}, OTP ${{matrix.otp}})

    strategy:
      matrix:
        otp: ["25", "26", "27"]
        elixir: ["1.16", "1.17", "1.18"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Fetch Elixir deps
        run: mix deps.get

      - name: Compile Elixir deps
        run: mix deps.compile

      - name: Run unit test
        run: mix test
